# .streamlit/config.toml
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"

[server]
headless = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
showToolbar = false

